Presentation/WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

[Route("[controller]")]
public class HomeController : Controller
{
    [HttpGet("/")]
    [HttpGet("about")]
    public IActionResult About()
    {
        return View();
    }

    public IActionResult RouteNotFounded()
    {
        return View();
    }
}

Presentation/WebApp/Controllers/PlayerController.cs
using Logic.Models.Requests;
using Logic.Models.Responses;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

[Route("players")]
public class PlayerController : Controller
{
    private readonly IPlayerService playerService;
    private readonly ITeamService teamService;

    public PlayerController(IPlayerService playerService, ITeamService teamService)
    {
        this.playerService = playerService;
        this.teamService = teamService;
    }

    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var result = await playerService.GetAllAsync();

        return result.IsSuccess
            ? View(result.Value)
            : GetErrorView(result.Error);
    }


    [HttpGet("create")]
    public async Task<IActionResult> Create()
    {
        var teamsResult = await teamService.GetAllAsync();
        if (!teamsResult.IsSuccess)
            return GetErrorView(teamsResult.Error);

        ViewData["Teams"] = teamsResult.Value;

        return View();
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create([FromForm] CreatePlayerRequest model)
    {
        if (ModelState.IsValid)
        {
            var result = await playerService.CreateAsync(model);
            return result.IsSuccess
                ? View("Success")
                : GetErrorView(result.Error);
        }

        var teamsResult = await teamService.GetAllAsync();
        if (!teamsResult.IsSuccess)
            return GetErrorView(teamsResult.Error);

        ViewData["Teams"] = teamsResult.Value;

        return View(model);
    }

    [HttpGet("update/{id:long}")]
    public async Task<IActionResult> UpdateAsync([FromRoute] long id)
    {
        var player = await playerService.GetAsRequestAsync(id);
        if (!player.IsSuccess)
            return GetErrorView(player.Error);

        var teamsResult = await teamService.GetAllAsync();
        if (!teamsResult.IsSuccess)
            return GetErrorView(teamsResult.Error);

        ViewData["Teams"] = teamsResult.Value;

        return View(player.Value);
    }

    [HttpPost("update/{id:long}")]
    public async Task<IActionResult> UpdateAsync([FromRoute] long id, [FromForm] CreatePlayerRequest model)
    {
        if (!ModelState.IsValid)
            return View(model);

        var result = await playerService.UpdateAsync(id, model);

        return result.IsSuccess
            ? RedirectToAction(nameof(GetAll))
            : GetErrorView(result.Error);
    }

    [HttpPost("delete/{id:long}")]
    public async Task<IActionResult> Delete(long id)
    {
        var result = await playerService.DeleteAsync(id);
        return result.IsSuccess
            ? RedirectToAction(nameof(GetAll))
            : GetErrorView(result.Error);
    }

    private ViewResult GetErrorView(string message)
    {
        return View("Error", new ErrorViewModel(message));
    }
}

Presentation/WebApp/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

public class TeamController : Controller
{
    
}

Presentation/WebApp/Views/Home/About.cshtml
@model dynamic

@{
    ViewBag.Title = "О проекте";
}

<h2>О проекте</h2>
<p>
    Данный сайт представляет Web-приложение "Каталог футболистов 3.0"
</p>

<p>
    <a href="https://github.com/MNYOU/CatalogOfFootballers">GitHub</a>
</p>

Presentation/WebApp/Views/Home/RouteNotFounded.cshtml
@model dynamic

@{
    ViewBag.Title = "Страница не найдена";
}

<h2>Страница не найдена!</h2>

Presentation/WebApp/Views/Player/Create.cshtml
@using Dal.Enums
@model Logic.Models.Requests.CreatePlayerRequest

@{
    ViewBag.Title = "Добавить футболиста";
}

<h2>Форма добавления футболиста</h2>
<form asp-controller="Player" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="FirstName" class="text-field_label"></label>
        <span asp-validation-for="FirstName" class="text-danger"></span>
        <input asp-for="FirstName" class="text-field_input">
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="text-field_label"></label>
        <span asp-validation-for="LastName" class="text-danger"></span>
        <input asp-for="LastName" class="text-field_input">
    </div>
    <div class="form-group">
        <label asp-for="Gender" class="text-field_label"></label>
        <span asp-validation-for="Gender" class="text-danger"></span>
        <select asp-for="Gender" asp-items="@Html.GetEnumSelectList(typeof(Gender))" id="cat">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Birthday" class="text-field_label"></label>
        <span asp-validation-for="Birthday" class="text-danger"></span>
        <input asp-for="Birthday" class="text-field_input" value="2020-12-02">
    </div>
    <div class="form-group">
        <label asp-for="Team.Name" class="text-field_label"></label>
        <span asp-validation-for="Team.Name" class="text-danger"></span>
        <input asp-for="Team.Name" class="text-field_input" list="teams"/>
        <datalist id="teams">
            @if (ViewData["Teams"] is IEnumerable<TeamView> teams)
            {
                foreach (var team in teams)
                {
                    <option value="@team.Name" selected="@(team.Name == Model?.Team?.Name ? "selected" : "")"></option>
                }
            }
        </datalist>
    </div>
    <div class="form-group">
        <label asp-for="Country" class="text-field_label"></label>
        <span asp-validation-for="Country" class="text-danger"></span>
        <select asp-for="Country" asp-items="@Html.GetEnumSelectList(typeof(Country))">
        </select>
    </div>
    <input class="btn" type="submit" value="Отправить">
</form>

Presentation/WebApp/Views/Player/GetAll.cshtml
@model IEnumerable<Logic.Models.Responses.PlayerView>?

@{
    ViewBag.Title = "Список футболистов ";
}

<div>
    <h2>Актуальный список добавленных футболистов</h2>
    <table class="table">
        <thead>
        <tr>
            <th>@Html.DisplayNameFor(x => x.FirstName)</th>
            <th>@Html.DisplayNameFor(x => x.LastName)</th>
            <th>@Html.DisplayNameFor(x => x.Gender)</th>
            <th>@Html.DisplayNameFor(x => x.Birthday)</th>
            <th>@Html.DisplayNameFor(x => x.Team)</th>
            <th>@Html.DisplayNameFor(x => x.Country)</th>
            <td></td>
        </tr>
        </thead>
        <tbody>
        @if (Model != null)
        {
            @foreach (var footballer in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => footballer.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => footballer.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => footballer.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(x => footballer.Birthday)
                    </td>
                    <td>
                        @Html.DisplayFor(x => footballer.Team.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(x => footballer.Country)
                    </td>
                    <td>
                        <form class="inline" asp-action="Update" method="get" asp-route-id="@footballer.Id">
                            <input class="btn" type="submit" value="Редактировать">
                        </form>
                        <form class="inline" asp-action="Delete" method="post" asp-route-id="@footballer.Id">
                            <input class="btn" type="submit" value="Удалить">
                        </form>

                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

Presentation/WebApp/Views/Player/Success.cshtml
@model dynamic

@{
    ViewBag.Title = "Успешно выполнено";
}
<div id="content">
    <h2>Футболист успешно добавлен</h2>
</div>

Presentation/WebApp/Views/Player/Update.cshtml
@using Dal.Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Logic.Models.Requests.CreatePlayerRequest

@{
    ViewBag.Title = "Редактирование";

    var birthday = Model?.Birthday?.ToString("yyyy-MM-dd");
}

<h2>Редактировать футболиста</h2>

<form asp-controller="Player" asp-action="Update" method="post" asp-route-id="@ViewContext.RouteData.Values["id"]">
    <div class="form-group">
        <label asp-for="FirstName" class="text-field_label"></label>
        <span asp-validation-for="FirstName" class="text-danger"></span>
        <input asp-for="FirstName" class="text-field_input">
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="text-field_label"></label>
        <span asp-validation-for="LastName" class="text-danger"></span>
        <input asp-for="LastName" class="text-field_input" value="@Model?.LastName">
    </div>
    <div class="form-group">
        <label asp-for="Gender" class="text-field_label"></label>
        <span asp-validation-for="Gender" class="text-danger"></span>
        <select asp-for="Gender" asp-items="@Html.GetEnumSelectList<Gender>()">
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Birthday" class="text-field_label"></label>
        <span asp-validation-for="Birthday" class="text-danger"></span>
        <input asp-for="Birthday" class="text-field_input" value="@birthday">
    </div>
    <div class="form-group">
        <label asp-for="Team.Name" class="text-field_label"></label>
        <span asp-validation-for="Team.Name" class="text-danger"></span>
        <input asp-for="Team.Name" class="text-field_input" list="teams">
        <datalist id="teams">
            @if (ViewData["teams"] is IEnumerable<TeamView> teams)
            {
                foreach (var team in teams)
                {
                    <option value="@team.Name" selected="@(team.Name == Model?.Team?.Name ? "selected" : "")"></option>
                }
            }
        </datalist>
    </div>
    <div class="form-group">
        <label asp-for="Country" class="text-field_label"></label>
        <span asp-validation-for="Country" class="text-danger"></span>
        <select asp-for="Country" asp-items="@Html.GetEnumSelectList<Country>()">
        </select>
    </div>
    <input class="btn" type="submit" value="Сохранить изменения"/>
    <a class="btn" asp-controller="Player" asp-action="GetAll">Вернуться к списку</a>
</form>

Presentation/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="About">
                <img class="navbar-toggler-icon icon" src="/images/ball.png" alt="мяч-иконка">Каталог футболистов 3.0
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item nav-link">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Create">Добавить футболиста</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="GetAll">Список всех футболистов</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="content pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Каталог футболистов 3.0
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>